[package]
name = "rtcsms"
version = "0.1.0"
authors = ["Gregory Eric Sanderson <gsanderson@jive.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
native-tls = "0.2"
chrono = "0.4"
